apiVersion: apps/v1
kind: Deployment
metadata:
  name: task4
spec:
  replicas: 4
  selector:
    matchLabels:
       env: production
#    matchExpressions:
#      - { key: env,  operator: In,  values: [ production ] }
  template:
    metadata:
     name: myweb-pod
     labels:
       env: production
    spec:
      containers:
      - name: myweb-con
        image: httpd
